services:
  postgres_ekos:
    image: postgres:alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: exaudie-db
    volumes:
      - exaudie_vol:/data_data
    networks:
      - exaudie_net

networks:
  exaudie_net:

volumes:
  exaudie_vol:
    driver: local
